require "../persistence"
require "pg"

module Movie
  module Persistence
    class BackendConfigurationError < Exception
    end

    # Shared PostgreSQL backend. Every Movie node opens its own bounded pool,
    # while database constraints arbitrate revisions and operation ids.
    class PostgresBackend < Backend
      getter uri : String

      def initialize(@uri : String)
        unless @uri.starts_with?("postgres://") || @uri.starts_with?("postgresql://")
          raise BackendConfigurationError.new(
            "persistence.connection-uri must be a postgres:// or postgresql:// URI"
          )
        end
      end

      def name : String
        "postgres"
      end

      def connect : BackendConnection
        PostgresBackendConnection.new(DB.connect(@uri))
      end
    end

    class PostgresBackendConnection < SqlBackendConnection
      SCHEMA_LOCK_ID       = 0x4d4f564945505253_i64
      EVENT_COMMIT_LOCK_ID = 0x4d4f564945455654_i64
      @bound_sql = {} of String => String

      protected def bind_sql(statement : String) : String
        @bound_sql[statement] ||= begin
          index = 0
          String.build(statement.bytesize + 8) do |io|
            statement.each_char do |char|
              if char == '?'
                index += 1
                io << '$' << index
              else
                io << char
              end
            end
          end
        end
      end

      protected def with_schema_lock(connection : DB::Connection, &operation : -> T) : T forall T
        connection.query_each(
          "SELECT pg_advisory_lock(#{SCHEMA_LOCK_ID})"
        ) { |row| row.read }
        yield
      ensure
        unless connection.closed?
          connection.query_one(
            "SELECT pg_advisory_unlock(#{SCHEMA_LOCK_ID})",
            as: Bool
          )
        end
      end

      protected def serialize_event_commit(connection : DB::Connection) : Nil
        connection.query_each(
          "SELECT pg_advisory_xact_lock(#{EVENT_COMMIT_LOCK_ID})"
        ) { |row| row.read }
      end

      protected def current_epoch_ms_sql : String
        "CAST(EXTRACT(EPOCH FROM clock_timestamp()) * 1000 AS BIGINT)"
      end

      protected def fence_validation_lock_sql : String
        " FOR UPDATE"
      end

      protected def table_exists?(connection : DB::Connection, name : String) : Bool
        !connection.query_one?(
          bind_sql("SELECT table_name FROM information_schema.tables " +
                   "WHERE table_schema = current_schema() AND table_name = ?"),
          args: [name] of DB::Any,
          as: String
        ).nil?
      end

      protected def table_columns(connection : DB::Connection, name : String) : Array(String)
        connection.query_all(
          bind_sql("SELECT column_name FROM information_schema.columns " +
                   "WHERE table_schema = current_schema() AND table_name = ? ORDER BY ordinal_position"),
          args: [name] of DB::Any,
          as: String
        )
      end

      protected def database_error?(error : Exception) : Bool
        error.is_a?(PQ::PQError) || error.is_a?(PG::Error)
      end

      protected def create_event_feed_table(connection : DB::Connection) : Nil
        connection.exec(<<-SQL)
          CREATE TABLE IF NOT EXISTS event_feed (
            event_offset BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            persistence_id TEXT NOT NULL,
            sequence_nr BIGINT NOT NULL,
            manifest TEXT NOT NULL,
            payload TEXT NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (persistence_id, sequence_nr)
          )
        SQL
      end

      protected def insert_event_feed(
        connection : DB::Connection,
        persistence_id : String,
        sequence_nr : Int64,
        manifest : String,
        payload : String,
      ) : Int64
        connection.query_one(
          "INSERT INTO event_feed (persistence_id, sequence_nr, manifest, payload) " +
          "VALUES ($1, $2, $3, $4) RETURNING event_offset",
          persistence_id,
          sequence_nr,
          manifest,
          payload,
          as: Int64
        )
      end

      protected def create_outbox_table(connection : DB::Connection) : Nil
        connection.exec(<<-SQL)
          CREATE TABLE IF NOT EXISTS persistence_outbox (
            outbox_offset BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            message_id TEXT NOT NULL UNIQUE,
            persistence_id TEXT NOT NULL,
            operation_id TEXT NOT NULL,
            destination TEXT NOT NULL,
            manifest TEXT NOT NULL,
            payload TEXT NOT NULL,
            delivered BIGINT NOT NULL DEFAULT 0,
            attempts BIGINT NOT NULL DEFAULT 0,
            lease_owner TEXT,
            lease_until_epoch_ms BIGINT NOT NULL DEFAULT 0,
            last_error TEXT,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            delivered_at TIMESTAMP
          )
        SQL
      end

      protected def insert_outbox(
        connection : DB::Connection,
        persistence_id : String,
        operation_id : OperationId,
        entry : OutboxEntry,
      ) : Int64
        connection.query_one(
          "INSERT INTO persistence_outbox " +
          "(message_id, persistence_id, operation_id, destination, manifest, payload) " +
          "VALUES ($1, $2, $3, $4, $5, $6) RETURNING outbox_offset",
          entry.message_id,
          persistence_id,
          operation_id.value,
          entry.destination,
          entry.manifest,
          entry.payload,
          as: Int64
        )
      end

      protected def maintenance_backend_name : String
        "postgres"
      end

      protected def perform_maintenance(connection : DB::Connection) : Nil
        %w(
          movie_schema_migration event_journal event_feed projection_checkpoint
          snapshot_store durable_state journal_operation state_operation persistence_outbox
          shard_lease
        ).each do |table|
          connection.exec("VACUUM (ANALYZE) #{table}")
        end
      end
    end

    BackendRegistry.register("postgres") do |config|
      uri = config.get_string(Movie::ActorSystemConfig::PERSISTENCE_CONNECTION_URI, "")
      if uri.empty?
        raise BackendConfigurationError.new(
          "persistence.connection-uri is required when persistence.backend is postgres"
        )
      end
      PostgresBackend.new(uri).as(Backend)
    end
  end
end
